export const FETCH_WEATHER = "FETCH_WEATHER";
export const FETCH_WEATHER_START = "FETCH_WEATHER_START";
export const FETCH_WEATHER_SUCCESS = "FETCH_WEATHER_SUCCESS";
export const FETCH_WEATHER_FAIL = "FETCH_WEATHER_FAIL";

export const FETCH_CURRENT = "FETCH_CURRENT";
export const FETCH_CURRENT_START = "FETCH_CURRENT_START";
export const FETCH_CURRENT_SUCCESS = "FETCH_CURRENT_SUCCESS";
export const FETCH_CURRENT_FAIL = "FETCH_CURRENT_FAIL";
